version: '3.0'
services:
  spacex:
    image: 'mannheimworld/spacex:latest'
    network_mode: host
    volumes:
      - '/opt/mannheimworld/data/watchchain:/opt/mannheimworld/data/watchchain'
    command:
      - ./spacex
      - '--base-path'
      - /opt/mannheimworld/data/watchchain
      - '--chain'
      - rubik
      - '--port'
      - '30888'
      - '--name'
      - spacex-script
      - '--rpc-port'
      - '19933'
      - '--ws-port'
      - '19944'
      - '--execution'
      - 'WASM'
      - '--wasm-execution'
      - compiled
      - '--in-peers'
      - '75'
      - '--out-peers'
      - '75'
      - '--no-telemetry'
      - '--pruning'
      - '8000'
      - '--ws-max-connections'
      - '50000'
      - '--ws-external'
      - '--rpc-external'
      - '--rpc-cors'
      - 'all'
    logging:
      driver: json-file
      options:
        max-size: 500m
    container_name: spacex-watch
